.\" this was stolen from the debian default 'undocumented' man page for 'panel'
.TH BMUD 1 "October 1999" "Br0kE" "GNOME BMUD-0.5"
.SH NAME
BMUD: Br0kE's MUD client (GNOME version).
.SH SYNOPSIS
bmud [-V?] [--help] [--version] [other GNOME options...]
.SH DESCRIPTION
This program provides a GUI based medium for communicating with a MUD, MUSH, or
MOO server. This software is
.B ALPHA GRADE
software, so don't be suprised by bugs, crashes, and other oopses. Please report bugs
to
.IR br0ke@math.smsu.edu
.SH SEE ALSO
.BR GNOME (1),
.SH AUTHOR
Erik Greenwald <
.IR br0ke@math.smsu.edu
> <
.IR erik@smluc.org
>.
