/* Automatically generated by po2tbl.sed from bmud.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"Aliases loaded.\n", 2},
  {"There are not aliases to save!!\n", 3},
  {"Tried to save empty alias table!", 4},
  {"Alias table was already NULL!\n", 5},
  {"\
Recorded alias \"%s\"\n\
Associated action: %s\n", 6},
  {"Could not open file \"%s\" to save aliases!\n", 7},
  {"Aliases successfully saved to file \"%s\".", 8},
  {"Could not open \"%s\" for read!!", 9},
  {"alias_process(): akey: %s", 10},
  {"alias_process(): avalue: %s", 11},
  {"Undefined Alias.\n", 12},
  {"Black", 13},
  {"Grey", 14},
  {"Red", 15},
  {"Pink", 16},
  {"Green", 17},
  {"Light_Green", 18},
  {"Orange", 19},
  {"Yellow", 20},
  {"Blue", 21},
  {"Light_Blue", 22},
  {"Maroon", 23},
  {"Purple", 24},
  {"Cyan", 25},
  {"Light_Cyan", 26},
  {"Silver", 27},
  {"White", 28},
  {"MESSAGE", 29},
  {"ERROR", 30},
  {"Color allocation failed\n", 31},
  {"Unabled to open color file for writing\n", 32},
  {"Couldn't open color file, using defaults\n", 33},
  {"BMUD!", 34},
  {"Ok", 35},
  {"Apply", 36},
  {"Cancel", 37},
  {"Defaults", 38},
  {"Help", 39},
  {"Colors", 40},
  {"Font", 41},
  {"History", 42},
  {"Misc", 43},
  {"BMUD Serverlist", 44},
  {"Sorry, Couldn't open serverlist", 45},
  {"Br0kEs MUD Client", 46},
  {"Br0kEs mud client", 47},
  {"Connection Wizard", 48},
  {"Connect to a mud", 49},
  {"Connect...", 50},
  {"Disconnect", 51},
  {"Disconnect from a mud", 52},
  {"Preferences...", 53},
  {"Preferences", 54},
  {"Exit", 55},
  {"Exit bmud", 56},
  {"Equip...", 57},
  {"Equipment Window", 58},
  {"Map...", 59},
  {"the mud map", 60},
  {"About...", 61},
  {"_File", 62},
  {"_Tools", 63},
  {"_Help", 64},
  {"File", 65},
  {"C-Wizard", 66},
  {"Connect", 67},
  {"Tools", 68},
  {"Equip", 69},
  {"Map", 70},
  {"About", 71},
  {"Manual", 72},
  {"Host", 73},
  {"Port", 74},
  {"Could not find your home dir", 75},
  {"\
\n\
*** Can't connect - you didn't specify a host\n", 76},
  {"\
\n\
*** No port specified - assuming port 23\n", 77},
  {"\
\n\
*** Making connection to %s, port %s\n", 78},
  {"\
\n\
*** Connection closed.\n", 79},
  {"\
\n\
*** gethostbyname() failed! ***\n", 80},
  {"\
\n\
*** Connection established.\n", 81},
  {"\
\n\
*** 0 byte packet received\n", 82},
  {"Could not open prefs file, using defaults\n", 83},
  {"Saving session\n", 84},
  {"Unabled to open prefs file for writing\n", 85},
};

int _msg_tbl_length = 85;
